### ISSUE TITLE
How do we slow down Tesse-simulator ?

### ISSUE THREAD

**Issue by han-kyung-min** [MIT-TESSE/tesse-ros-bridge#3]
Hello,

I am trying to run a grid-map node (octomap) with this Tesse env. My problem is that the octomap node is slower than Tesse env, causing a sync problem when step() is processed. That is, I need to wait for the updated grid-map from octomap before proceeding a step() in my training script. However, the running speed of the Unity env is way too faster than octomap. 

One way of alleviating this problem might be slowing down the simulator. I tried both "speedup_factor" and "frame_rate" parameters, which are available in "tesse_ros_node.py." But, I wasn't able to make the simulator slow by tuning these parameters. 

Could you please give me a piece of advice to reduce down the speed of the simulator?

Best,

**Comment by ZacRavichandran** [comment]
Hello,

Step mode, which explicitly syncs time between the client (i.e., ROS) and the simulator, may help. With this, every time `step` is called the game will advance by `1/frame_rate` where `frame_rate` is defined in hertz . Thus, if you wait for the grid-map node to finish processing before calling `step`, the game will not advance too quickly. Step mode can be enabled by passing `enable_step_mode:=true` to the [launch file.](https://github.com/MIT-TESSE/tesse-ros-bridge/blob/master/launch/tesse_bridge.launch#L9). 

`speedup_factor`  handles time conversion from the simulator to ROS, but will not slow down the simulator. 

Hope this helps!

**Comment by han-kyung-min** [comment]
Thanks for your reply.

It appears to me that "frame_rate" parameter must be an integer, which means "1" is the minimum speed I can set. Can I go slower than 1 ? Or, is there any other way to slow down the game speed ?

Best,

**Comment by ZacRavichandran** [comment]
I haven't tried using a `frame_rate` below 1, but it may be worth trying.

However, `frame_rate` will not change the physical speed of the game. Rather, in step mode, each step will run for a duration of `1/frame_rate` in game time (see the tesse-core [docs](https://github.com/MIT-TESSE/tesse-core#timing-modes) for a short explanation). There isn't any other way to change game time. So, running in step mode and waiting for the grid-node process to finish before making subsequent `step` calls may be a solution.

**Comment by han-kyung-min** [comment]
OK. Thanks.
